### ISSUE TITLE
Brittle indentation

### ISSUE THREAD

**Issue by g2flyer** [skuro/plantuml-mode#103]
# Summary

The indentation is a bit brittle:
- currently a note where the content has a line starting with Note (not necessarily uncommon?) confuses indentation. Following regexp would seem more robust: "^\s*\\(floating\s+\\)?[hr]?note\s+\\(right\\|left\\|top\\|bottom\\|over\\)[^:]*?$"
- ref over are not handled properly when somewhat indented: plantuml-indent-regexp-ref-start should allow for preceeding spaces, e.g., "^\s*ref\s+over\s+[^:]+?$"?
- activations can also end via a destroy, not only deactivate, also the short-cuts with ++/-- activate/deactivate, so indentation is a bit inconsistent now.  Also, it's a matter of taste whether activations should lead to indentation. Would be nice to have an opt-out. 

- lastly a wild thought: there are probably always some corner cases where indentation will not work when using regexp rather than context-sensitve expressions: What might be helpful maybe in that case is some "magic expression"/pragma which one could stick into a comment which would allow overruling the auto-indentation (e.g., 'puml-rel-depth+1/puml-rel-depth-1)

PS: in any case, thanks for the mode!

**Comment by skuro** [comment]
Yeah, it's kinda known issue, I'd love to improve the handling and limit the extent to which regexps go but that's quite a major effort. Happy to receive any PR that improves on the topic.

**Comment by skuro** [comment]
I think this issue could be closed now that #105 has been merged, right?

**Comment by g2flyer** [comment]
Close as mostly covered with #105 (exception is third bullet "activations can also end via a destroy, not only deactivate, also the short-cuts with ++/-- activate/deactivate, so indentation is a bit inconsistent now")
