### ISSUE TITLE
condition-case: Symbol’s function definition is void: first

### ISSUE THREAD

**Issue by kaiwk** [skuro/plantuml-mode#106]
Execute 'plantuml-download-jar'，it throws the error below: 

> Symbol’s function definition is void: first

**Comment by skuro** [comment]
I don't seem to be able to reproduce it, can you please share some details of your environment?

- plantuml-mode version
- OS
- emacs version

**Comment by kaiwk** [comment]
Sorry for missing such info.

- plantuml-mode-version: 1.3.1
- emacs version: GNU Emacs 26.2
- OS: Mac OS X

stack trace: 
>Debugger entered--Lisp error: (void-function first)
  first(((str ((name . "v")) "1.2019.8")))
  plantuml-download-jar()
  funcall-interactively(plantuml-download-jar)
  #<subr call-interactively>(plantuml-download-jar record nil)
  apply(#<subr call-interactively> plantuml-download-jar (record nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> plantuml-download-jar record nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (plantuml-download-jar record nil))
  call-interactively(plantuml-download-jar record nil)
  command-execute(plantuml-download-jar record)
  helm-M-x(nil "plantuml-download-jar")
  funcall-interactively(helm-M-x nil "plantuml-download-jar")
  #<subr call-interactively>(helm-M-x nil nil)
  apply(#<subr call-interactively> helm-M-x (nil nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> helm-M-x nil nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (helm-M-x nil nil))
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)

**Comment by skuro** [comment]
For some reason, in my setup `first ` is an alias to `car`, but I cannot spot where the alias is actually established...

Anyways, I created a [new branch](https://github.com/skuro/plantuml-mode/tree/issue106) with a potential fix for your issue, pretty much renaming `first` into `car`. You could either try out code from that branch or redefine the download function using this version:

```emacs
(defun plantuml-download-jar ()
  "Download the latest PlantUML JAR file and install it into `plantuml-jar-path'."
  (interactive)
  (if (y-or-n-p (format "Download the latest PlantUML JAR file into %s? " plantuml-jar-path))
      (if (or (not (file-exists-p plantuml-jar-path))
              (y-or-n-p (format "The PlantUML jar file already exists at %s, overwrite? " plantuml-jar-path)))
          (with-current-buffer (url-retrieve-synchronously "https://search.maven.org/solrsearch/select?q=g:net.sourceforge.plantuml+AND+a:plantuml&core=gav&start=0&rows=1&wt=xml")
            (mkdir (file-name-directory plantuml-jar-path) t)
            (let* ((parse-tree (xml-parse-region))
                   (doc        (->> parse-tree
                                    (assq 'response)
                                    (assq 'result)
                                    (assq 'doc)))
                   (strs       (xml-get-children doc 'str))
                   (version    (->> strs
                                    (--filter (string-equal "v" (xml-get-attribute it 'name)))
                                    (car)
                                    (xml-node-children)
                                    (car))))
              (message (concat "Downloading PlantUML v" version " into " plantuml-jar-path))
              (url-copy-file (format "https://search.maven.org/remotecontent?filepath=net/sourceforge/plantuml/plantuml/%s/plantuml-%s.jar" version version) plantuml-jar-path t)
              (kill-buffer)))
        (message "Aborted."))
    (message "Aborted.")))
```

If any of the above methods work for you I'll just merge the changes in.

**Comment by kaiwk** [comment]
It works, thank you!

**Comment by skuro** [comment]
Thank you for testing! Code was merged in, a new release will be available soon at MELPA unstable, will probably cut a release for MELPA stable later today as well
