### ISSUE TITLE
plantuml-server-preview-string: Multibyte character in data for base64 encoding

### ISSUE THREAD

**Issue by darcylee** [skuro/plantuml-mode#110]
# Summary

use `server` exec-mode, when there has cjk byte in uml source code, like chinese, Japanese. 
then < c-c c-c > preview get this error 

`plantuml-server-preview-string: Multibyte character in data for base64 encoding`

I just get this message [https://lists.gnu.org/archive/html/help-gnu-emacs/2012-04/msg00173.html](https://lists.gnu.org/archive/html/help-gnu-emacs/2012-04/msg00173.html)

I change `base64-encode-string` like this :`(base64-encode-string  (encode-coding-string string 'utf-8-unix) t)`
it is work fine for me.

**Comment by skuro** [comment]
@darcylee thank you for the bug report and the initial investigation. would you be able to test out pull request #111?

**Comment by darcylee** [comment]
> @darcylee thank you for the bug report and the initial investigation. would you be able to test out pull request #111?

still have problems

``` plantuml
@startuml
Bob -> Alice : 信息集合
@enduml
```
preview like this:

![image](https://user-images.githubusercontent.com/6210592/64094945-f1aa5480-cd8f-11e9-8013-e92f1c4185e2.png)

```
@startuml
Bob -> Alice : 銀行システム
@enduml
```

![image](https://user-images.githubusercontent.com/6210592/64095376-384c7e80-cd91-11e9-9641-3c8b4651f93e.png)


**But in this cace it seems to be correct**

@startuml
Bob -> Alice : 人民银行
@enduml

![image](https://user-images.githubusercontent.com/6210592/64095129-87de7a80-cd90-11e9-8835-610e41859f94.png)

**Comment by skuro** [comment]
Mhhh it seems like some more work needs to be done on encoding to make `plantuml-server` happy
