### ISSUE TITLE
The default value of plantuml-java-args doesn't work on java<1.9 when plantuml-default-exec-mode is set to 'jar

### ISSUE THREAD

**Issue by nott** [skuro/plantuml-mode#114]
I'm running emacs 26.3, openjdk 1.8.0_222 and plantuml-mode-20190822.1403

Whenever I'm trying to preview a diagram, I get the following output in plantuml preview window:
```
Unrecognized option: --illegal-access=deny
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

The issue is caused by commit 76b14086e8ff4bbbaa24f9ebd3f09fe746665011

The solution is to `(setq plantuml-java-args (list "-Djava.awt.headless=true" "-jar"))`

Taking into account people usually install the latest available plantuml-mode, but use their system-wide java, it would be great if the default configuration works out of the box on many versions of java or the workaround is properly documented.

(Please note that this is only relevant when `(setq plantuml-default-exec-mode 'jar)` is used)

**Comment by nott** [comment]
By the way, thanks a lot for plantuml-mode - it's a great package!

**Comment by skuro** [comment]
I'm experimenting with autodetection of the JDK, would you be able to give #115  a round of test and tell me if it works for you?

**Comment by skuro** [comment]
thanks for the kind words BTW, happy `plantuml-mode` proved useful to you

**Comment by nott** [comment]
@skuro i have just given it a try - that branch works for me
