### ISSUE TITLE
Re-use preview buffer.

### ISSUE THREAD

**Issue by mrtimdog** [skuro/plantuml-mode#119]
Don't delete the preview buffer before re-creating the preview, just clear it and re-use the same buffer. Otherwise the preview buffer re-appears all over the place when many other buffers are open.

I've added a pull request, although I'm fairly new to GitHub so probably missed or not linked something the proper way!

[https://github.com/skuro/plantuml-mode/pull/118](https://github.com/skuro/plantuml-mode/pull/118)

**Comment by skuro** [comment]
Seems to me like the pull request and the issue are just perfect, thanks :-)
I've commented on both code and pull request levels, let me know what you think of that

**Comment by usq** [comment]
I face the same issue as well. I use plantuml to create quite large sequence charts and end up with buffers all over the place...

**Comment by zhenwenc** [comment]
I think the solution should be simply don't kill the buffer when preview, [here](https://github.com/skuro/plantuml-mode/blob/develop/plantuml-mode.el#L487). What do you think?

**Comment by Digicrat** [comment]
+1

On a related note, I'm also seeing it randomly swapping buffers in the window containing my UML diagram source to the most recent file, while opening the preview in a different window.  

For example, if my frame is split into 2 windows, with the UML diagram source open on the right.  I then use C-c C-c to generate the preview which opens new preview window in the left, while simultaneously switching the right to show a different open file.  (This is in Aquamacs Emacs).

**Comment by zhenwenc** [comment]
See comments in this PR: https://github.com/skuro/plantuml-mode/pull/118

I managed to reuse the existing buffer with a custom hack similar to the above solution, but it causes weird effect when replacing the content of an image buffer (first render as text, then the image.. hurt my eyes...).

**Comment by Digicrat** [comment]
I found a workaround that achieves the desired effect (at least for my purposes) by configuring it to always open the preview in the same window (which can then be closed with the 'q' key).  Simply add the following to your .emacs:

```
  ;; Open in same window
  (add-to-list 'display-buffer-alist
               '("*PLANTUML Preview*" display-buffer-same-window)
               )
```

Looking at the plantuml-mode source, I see that if you want to open it in a different frame run "C-u C-c C-c", or add a second "C-u" to open in a new frame.

The plantuml-update-preview-buffer function can probably be updated to explicitly use display-buffer-same-window to make this the default behavior for all, but I'm not sure the syntax to do so.

**Comment by skuro** [comment]
no stale please

**Comment by muhuk** [comment]
It would be very nice to have this fixed. When a preview buffer is visible, its contents should be updated. Currently the mode is closing the preview buffer and then displaying the preview in a newly created window.
