### ISSUE TITLE
Wrapping uml in @startuml and @enduml org-babel blocks causes syntax error in svg output

### ISSUE THREAD

**Issue by vonHabsi** [skuro/plantuml-mode#121]
This is the cause of the problem resulting in issue #120.

When I installed plantuml-mode I copied the example which wraps the code in startuml/enduml tags into the org-babel block.

```
@startuml
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: Another authentication Response
@enduml
```

In more recent plantuml versions this causes some additional xml to be added to svg output.

It may be a good idea to note it so future users don't fall afoul of this feature of plantuml.

**Comment by skuro** [comment]
no stale pls

**Comment by eddiegroves** [comment]
I ran into this too, when copying existing diagram source into babel blocks.

**Comment by vonHabsi** [comment]
@eddiegroves Better raise it as new issue concerning documentation

**Comment by eddiegroves** [comment]
I've dug around some more and found my culprit was upstream https://github.com/hlissner/doom-emacs/issues/2441

**Comment by jmones** [comment]
I was hit by a similar (same?) issue. Leaving a message in case it helps others.

Plantuml seems to be a little bit picky when getting input from a pipe executing the jar (this is how `plantuml-mode` uses it if not using server mode). In this mode, it will fail if `@startuml`/`@enduml` are included and *there's any kind of data after `@enduml`*. That includes whitespace too.

Plantuml actually interprets this data as a new diagram, and outputs a second SVG (sometimes) or fails to recognise this data as a suitable diagram.

[Made a PR to plantuml](https://github.com/plantuml/plantuml/pull/600) (merged today) to improve a little bit how it handles that.  With this change it will:
* interpret as a graph if now tags
* reject anything. outside @start*/@end* if present

Note that if multiple tags are present, it will still send several graphs back. I don't know if `plantuml-mode` can handle that.
