### ISSUE TITLE
plantuml-preview-current-block should preserve cursor location

### ISSUE THREAD

**Issue by Digicrat** [skuro/plantuml-mode#123]
After exiting the preview opened by plantuml-preview-current-block, the cursor is always at the end of the '@enduml' tag (as a result of the search-* calls).  It should preserve the original cursor position (helpful when in the midst of editing a large diagram).

I'm not creating a PR, in part because I don't fully understand how the save-restriction and narrow-to-region functions work to (efficiently) fix the definition directly, but this should be an easy fix. 

As a workaround I defined the following function to give me the expected behavior:

```
(defun my-plantuml-preview-current-block ()
  (interactive)
  (setq initPt (point))
  (call-interactively 'plantuml-preview-current-block)
  (goto-char initPt)
  )
(define-key markdown-mode-map (kbd "C-c c") 'my-plantuml-preview-current-block)
```

**Comment by skuro** [comment]
no stale please
