### ISSUE TITLE
Only display stdout in preview

### ISSUE THREAD

**Issue by xeruf** [skuro/plantuml-mode#135]
Due to my JVM configuration, every run of `java` prints the following message to stderr:
```
Picked up _JAVA_OPTIONS: [...]
```

The problem is that that ends up in the preview buffer above the actual image - thus I have to always enter the buffer, remove the first line and press `C-cC-c` to view the actual image, which is super annoying.

I think stderr should never end up in there anyways...

See also https://superuser.com/questions/585695/suppressing-the-picked-up-java-options-message

**Comment by xeruf** [comment]
I tinkered a little, but my el-fu isn't good enough :/

**Comment by a1exsh** [comment]
I'm hitting a very similar issue, but the `stderr` contains the following:
`[Log] "dynamic undefined legend colors" requires PlantUML version >= 1.2021.6, therefore only static assigned colors are used`

This, not unexpectedly, breaks the preview.

Fixing it will require moving away from `start-process` to `make-process`, it seems.

**Comment by mark-climateview** [comment]
Had the same problem using `plantuml-c4` installed by nix (as an executable binary, so no .jar file). I was able to solve it using make-process with:

```
(defun plantuml-executable-start-process (buf)
  "Run PlantUML as an Emacs process and puts the output into the given buffer (as BUF) and sends any stderr output to an error buffer."
  (make-process
   :name "PLANTUML"
   :buffer buf
   :stderr (get-buffer-create "*PLANTUML-Error*")
   :command (append (list plantuml-executable-path)
                    plantuml-executable-args)))
```
