### ISSUE TITLE
plantuml jar exec mode 

### ISSUE THREAD

**Issue by rese17** [skuro/plantuml-mode#138]
# Summary
i get this error even though the plantuml.jar file works fine outside emacs 
error in process sentinel: PLANTUML Preview failed: exited abnormally with code 200
> Write here the summary of your changes

**Comment by mcraveiro** [comment]
I suspect your configuration may not be quite right. Can you share it here please? In particular, ```plantuml-default-exec-mode``` and ```plantuml-jar-path```.
