### ISSUE TITLE
Proper preview support for Windows users

### ISSUE THREAD

**Issue by skuro** [skuro/plantuml-mode#14]
As mentioned in #10, `puml-mode` fails to render diagrams when running on Windows due to the different path management it requires.

Provide a fix that doesn't require end users to implement dirty hacks.

**Comment by iquiw** [comment]
How about just removing `shell-quote-argument`?
as `start-process` does not use shell.

**Comment by iquiw** [comment]
Ah, there is `shell-command` in `puml-init`, which requires `shell-quote-argument`.
I think it can be replaced with `call-process` though.

**Comment by abcdec** [comment]
maybe fixed by combination of PR #40 and #41 ..

**Comment by skuro** [comment]
There has been little activity on `plantuml-mode`, but as I'll try to pay a bit more attention to it I'd like to groom this one. @abcdec might be right saying that the merged PRs might fix the issue. If anyone can verify the current status (testing on Windows for me is much of an annoyance), please speak up, or I'll close this one and wait for a new bug report.

**Comment by iquiw** [comment]
I'm using `plantuml-mode` on Windows and see no problem about `plantuml-jar-path`.

**Comment by skuro** [comment]
Thanks @iquiw, in this case I'll close the issue for now and wait for the next bug report.
