### ISSUE TITLE
just sharing a patch to preview the result in a "coolish way"

### ISSUE THREAD

**Issue by mickael-kerjean** [skuro/plantuml-mode#15]
Hello,

On the current version of the mode, if I press C-c, it creates a new buffer and render the result filling all my screen.
As I would have love the approach shown [here](https://raw.githubusercontent.com/skuro/puml-mode/master/banner.png) where the rendering result appear on the right side of the screen and can be update (by pressing C-c again) or close (by pressing q), I made a few changes to the source code.

[Here it is](https://gist.github.com/mickael-kerjean/915d76b9d22a3ff8ad8f#file-puml-mode-el). 
Nothing fancy, just using the display-buffer function from emacs and update the relevant code to make it works properly.

I have this patch in puml-mode since a few weeks and it works ok.

**Comment by skuro** [comment]
Hey @mickael-kerjean, that seems like a nice improvement in the workflow of using `puml-mode`. However, in my local testing something goes a bit sideways: 

- on a `.puml` buffer, hit `C-c C-c`
- the buffer shows with the diagram (all right so far)
- back to the `.puml` buffer, I make some changes
- hit again `C-c C-c` to update the buffer

Expected: 
- I see the updated diagram

Actual:
- I see an empty diagram (switching to the text mode with `C-c C-c` on the diagram buffer also shows an empty buffer)

I'll try to debug further, maybe something is going wrong with buffer management, but at the moment that's a show stopper to integrate your patch.

Besides, if you could make a PR out of your changes it would make it easier for me to work on it ;-)

**Comment by mickael-kerjean** [comment]
That's quite funny, I use this version nearly everyday and it is working as expected (windows machine).
The image update simply using C-c C-c, no empty diagram at all.

I didn't create a PR as I had to patch the code to make the mode working on windows. Will create one in a few seconds if you want

**Comment by skuro** [comment]
`C-u C-c C-c` currently accomplishes what you ask for. Closing.
