### ISSUE TITLE
Merge with `plantum-mode.el`

### ISSUE THREAD

**Issue by skuro** [skuro/plantuml-mode#26]
As [agreed by the original author](https://github.com/zwz/plantuml-mode/issues/8) of `plantuml-mode`, we need to merge our repositories. This involves: 

- comparing features and merge all of them
- rename `puml-mode` into `plantuml-mode`
- update [MELPA](https://github.com/melpa/melpa/blob/master/recipes/plantuml-mode)

**Comment by skuro** [comment]
@zwz as far as I could see the main feature that your `plantuml-mode` had which was still missing here was the ability to render a selected region instead of a complete buffer. I just pushed it to the `feature/merge-repositories` branch, if you had any time to check.

**Comment by skuro** [comment]
@zwz the migration seems now complete to me in the `feature/merge-repositories` branch. I'll wait for some feedback this week, after which I'll proceed updating MELPA to use my repository for `plantuml-mode`.

**Comment by terlar** [comment]
Most stuff looks good, but I would like to be able to choose format, or most preferably solve the bug, it seems I can't get it work with the svg format. However I have verified that my emacs can open other svg files and that the plantuml command can output correct svg files. How could that be?

I also found that the `plantuml-run-command` is not utilized, I would like to use that to add:
```
java -Djava.awt.headless=true -jar %s
```

So it runs the command in headless and don't have to see that flashing image processing.

**Comment by terlar** [comment]
Actually I commented out the svg part in your version and it didn't work with png either. But it worked in the zwz script.

**Comment by terlar** [comment]
Ah! I found the issue:

I am using the exported variable `_JAVA_OPTIONS`, since this is outputted in the beginning of the command it fails the output. So my files look something like this:

```
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
<?xml version="1.0" encoding="UTF-8" standalone="no"?><svg xmlns="http://www.w3.org/2000/svg" ...
```

**Comment by terlar** [comment]
So it is reported to stderr, but there seems to be no good way to filter that out, perhaps I just have to create a wrapper script.

http://emacs.stackexchange.com/questions/17394/discard-stderr-in-start-process

Let me know if you have any ideas.

**Comment by skuro** [comment]
Hi @terlar. In the merge I was trying to use `plantuml-run-command`, but as the preview executes PlantUML with `start-process` I need to provide as the first argument the actual executable (i.e. `java`) which is actually looked up in the exec `PATH`. 
I will try to think of a better way of doing so, but I think your comments warrant a dedicated enhancement issue (read: let's fix this after the merge) to allow custom exec commands to be configured. Care to submit one?

RE: the rendering issue with SVG, I'll run a few experiments and let you know if I find anything on my side.

**Comment by skuro** [comment]
@terlar in my tests SVG preview works flawlessly: I can select SVG from `plantuml-set-output-type` and then `C-c C-c` to run the preview. 

What I did find is that the code included a bug introduced with the support of preview for the currently selected region: if you select text, the preview will only be done on the selection. Problem was, I was using `(if (mark) ...` instead of `(if mark-active ...`, which would trigger old regions to be rendered (see ae0f582).

Could you please try again with the new code and tell me if you are now able to render SVG previews?

**Comment by terlar** [comment]
If you see my comment:

https://github.com/skuro/puml-mode/issues/26#issuecomment-253554361
 and https://github.com/skuro/puml-mode/issues/26#issuecomment-253558245

The issue is not with rendering the SVG previews, the issue was the the pipe includes both output to stderr and stdout, and java if you have set the environemnt variable `_JAVA_OPTIONS`, it will print that to stderr as you launch the java command.

You can try doing:
```
export _JAVA_OPTIONS="-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel"
emacs
```

and then try to preview a PlantUML-file.

I just misunderstood from the beginning, I thought that it was something wrong with the viewing, but it was actually that the pipe got these extra data from stderr.

I am not very proficient in elisp, but I could take a stab at it. One way would be if it was possible to pipe to `2>/dev/null` first, that would get rid of the errors, but not sure how to do that in elisp.

**Comment by skuro** [comment]
Oh! Now I understand it! That seems indeed to be a tough cookie..

A potential fix could be to replace `start-process` with `make-process`, which has a `:stderr` option to redirect it elsewhere (e.g. the `*PlantUML Messages*` buffer). But alas, [that would only work in Emacs 25+](http://emacs.stackexchange.com/a/12456/9628), which is a bit too young to embrace it as the minimum version.

In my [last commit](a324da362adf2c7a0deb526db97a08d1b8e37e49) I introduced a custom variable for the `java` executable. This allows you to create a shell script somewhere in your `exec-path` as suggested on SO:

```
$ cat `which java-nostderr`
#!/bin/bash
java $@ 2>/dev/null
exit $?
```

In my local testing I was able to replicate your issue (it also screws up the keyword list / highlighting by the way) and to fix it by  `customize-variable` `plantuml-java-command` to use `java-nostderr`. Let me know if it works for you as well!

**Comment by skuro** [comment]
@terlar Incidentally, the last fix also supports adding the `-Djava.awt.headless=true` flag in the external shell script, something you were asking up above.

**Comment by terlar** [comment]
@skuro yes, I was thinking the same regarding `:stderr`, for now this will work for me, I have created a custom java wrapper-script that I can use through the new `plantuml-java-command`.

Now the only thing is the warning that pops up all the time that was added in these commits:
```
Warning (:warning): `plantuml-mode' is deprecated in favor of `plantuml-mode', make sure to update your configuration
```

Should that really happen? It is a bit annoying, for now I have just removed that line from the script. Otherwise that pops up every time I load a plantuml file.

Thanks for the work and effort btw, I just found out about PlantUML yesterday and was really happy to have this plugin inside emacs.

**Comment by skuro** [comment]
You are right, the warning should not happen on `plantuml-init`. I now synchronized both `feature/pre-merge` and `feature/merge-repository` branches so that the warning is triggered with a hook on the mode itself iff `puml-mode` is a loaded feature. That should get rid of the message for you, now.

If no other issues pop up before then, on Sunday I'll publish the code as the new `plantuml-mode` on MELPA.

-------- [OT] --------
On a side note: no need to thank me, you are truly being an awesome beta tester :-)

Myself, I've been fiddling with PlantUML for a few years now, and this is my first real elisp project (and the bulk of the current code actually comes from @zwz). I desperately needed a @terlar of the world to help me out on the testing side of things!
-------- [/OT] --------

**Comment by skuro** [comment]
The merge is now done. MELPA has the new updated `plantuml-mode`. The world is a better place now. <3

**Comment by zwz** [comment]
@skuro It is good to hear that the merge job is done. I will give a notice on my page and direct people here.

**Comment by skuro** [comment]
@zwz that's great, thank you so much!
