### ISSUE TITLE
Avoid JVM startup

### ISSUE THREAD

**Issue by skuro** [skuro/plantuml-mode#27]
Find a way to avoid waiting time for the JVM startup at every execution.

Possible strategies:
- [nailgun](https://github.com/martylamb/nailgun)
- [telnet server](https://github.com/plantuml/plantuml/blob/6e2c2c32c961fe5952a04f7dbbe689216d42e87a/src/net/sourceforge/plantuml/telnet/TelnetServer.java)
- [FTP server](https://github.com/plantuml/plantuml/blob/b165be16e3724f53025e787c0d9c8f4bb01408e7/src/net/sourceforge/plantuml/ftp/FtpLoop.java)

**Comment by abcdec** [comment]
I guess you can just pre-launch java and pend on standard input as soon as mode is invoked and whenever previous processing is done?

**Comment by skuro** [comment]
@abcdec that's indeed the idea, but as I'd avoid having to write any java code to wrap PlantUML executions, we can only use what's in the package (i.e. the PlantUML JAR). That's why I was looking at the telnet / ftp server. Even nailgun seems a bit overcomplicated, as it requires more JARs than PlantUML itself.

There are also tools like [drip](https://github.com/flatland/drip), but again extra dependencies are not handy, and in my experience similar tools are a bit brittle in the long run.

**Comment by abcdec** [comment]
I meant doing it inside emacs lisp.  No java wrapper.  Well, it still starts java every generation anyway, but have emacs to run java almost always when the user is ready to send string.  

An example coded here diff on top of other changes:
https://github.com/abcdec/plantuml-mode/tree/example-pre-launch
Or see diff:
https://github.com/abcdec/plantuml-mode/pull/1/files

At very first time of rendering, it will launch a java process that runs plantuml diagram generation then exits. But 3sec later after generation is done, start another java in background, pending on input in stdin. Do this every time diagram is generated and java exits. This way java is in most cases loaded in memory and ready to serve when user types C-cC-c. (if needed we can make this a server pool, like prelaunch N number of java processes always and maintain server pool to avoid the cases java launching is needed upon C-cC-c..)

But having said this, I am not sure how much benefit we get. Seems like actual start up is not taking long time esp. when java and jar file is in memory cache.  Still processing of input and generating diagram itself seems to be the part that taking time.  This might not give noticeable performance improvement.

If you have a remote processing server cluster in your network that provides high processing power that will provide much faster rendering, I guess you can create a wrapper command to dispatch remote execution of java via SSH and replace plantuml-java-command. You can also pursue your ideas of using the mentioned external packages, they are certainly options. I'd hope it will not create too much dependencies or complications in plantuml-mode.el. It would be good to keep plantuml-mode.el compact and self contained.

**Comment by skuro** [comment]
Thats seems a promising approach indeed, seems like I misinterpreted you at the beginning. Not sure how it would all play along having multiple PlantUML files being rendered at alternate times?

I still sort of feel like using the [Telnet server](https://github.com/plantuml/plantuml/blob/6e2c2c32c961fe5952a04f7dbbe689216d42e87a/src/net/sourceforge/plantuml/telnet/TelnetServer.java) might be the easiest option here since it's already provided by PlantUML. Still need to investigate if that gives us any limitation (e.g. output type selection), and surely it also brings the need for persistent process management.

On the performance topic, would you be able to sort of benchmark the one-process-per-preview that we have now in master with the preload-jvm-after-render that you implemented in terms of latency?

**Comment by abcdec** [comment]
You can start multiple Java processes in the same way for different options and buffer name as a process name, like "PLANTUML-sample.pum-png" and if there find matching process use it otherwise launch it then re-launch.  Several different way to manage multiple Java instances for different plantuml source buffer.  If you have three files, potentially 3 java spawned waiting for standard input. You chose whichever users preview needs.  A java process loaded with plantuml.jar seems to use about 18MB, so creating every source file may not be a good idea, in such case, just create a pool of "LANTUML-png-#" like "PLANTULM-png-1", "PLANTUML-png-2", ... then take one available. Then if 20 files open, you don't use 18MB x 20, but say 18MB x 4. (In case 4 java pre-launch pool.)

Quick ELP results i7-2630QM 2GHz Windows 10 + cygwin64 emacs + Native Java 8.  Launch time is <150ms first time and <100ms for 29 repeat average. Note this result does not give the time of plantuml processing since sentinel execution will work like callback, so ELP would not be able to catch actual elapsed time java spent for input processing.  Need some embedded codes to record timestamp at each eof sending time and the time when the sentinel is called.  If time allows I can do the experiment.

First time
```
Function Name                        Call Count  Elapsed Time  Average Time
plantuml-launch-process-file-output  2           0.1183287000  0.0591643500
plantuml-file-output                 1           0.0606688     0.0606688
```
Retest first time
```
Function Name                        Call Count  Elapsed Time  Average Time
plantuml-launch-process-file-output  2           0.1251690999  0.0625845499
plantuml-file-output                 1           0.0615271     0.0615271
```

29 times iteration
```
Function Name                        Call Count  Elapsed Time  Average Time
plantuml-launch-process-file-output  58          1.8672446999  0.0321938741
plantuml-file-output                 29          0.0127488999  0.0004396172
```

WRT Telnet, one thing to keep in mind would be that opening networking port always come with security concern, multi-user port conflict resolution, etc. which might require the users additional burden such as configuring firewall, reserving service port, coordinating with other users on use of the same server port in multi-user environment, etc.

**Comment by abcdec** [comment]
Rendering simple 4 lines SD with https://github.com/abcdec/plantuml-mode/commit/f9bde7b5d0ac3e96394c49bc7ffe6cea30ff1021 code:
```
DHCPCLIENT ->> DHCPSERVER : DHCPDISCOVER
DHCPCLIENT <-- DHCPSERVER : DHCPOFFER
DHCPCLIENT ->> DHCPSERVER : DHCPREQUSET
DHCPCLIENT <-- DHCPSERVER : DHCPACK
```
Result of 30 times run:

```
*elapsed-time*
17.133850600000006

*elapsed-time-count*
30

(/ *elapsed-time* *elapsed-time-count*)
0.5711283533333336
```

Average 571ms - this will become longer if SD becomes complex.

Rendering a bit more involved sequence diagram below, taking 824ms in average:

```
actor User

User -> Emacs : C-cC-c
activate Emacs
note over Emacs : plantuml-preview-string running
opt not yet started
Emacs -> Java : process-start(plantuml.jar)
activate Java
Emacs <-- Java : process identifier
end opt
Emacs ->> Java : Input String
Emacs ->> Java : EOF
User <-- Emacs : Control
deactivate Emacs
Java <<-- Java : Diagram Rendering
Emacs <<-- Java : Output Data
Java <<-- Java : exit()
Emacs <<-- Java : Child exit signal
deactivate Java
activate Emacs
note over Emacs : sentinel running
Emacs ->> Emacs : Image Rendering
User <-- Emacs : Rendered Image
deactivate Emacs
Emacs ->> Emacs : 3 sec timer
activate Emacs
opt not yet started
Emacs -> Java : process-start(plantuml.jar)
activate Java
Emacs <-- Java : process identifier
end opt
deactivate Emacs
note over Java : Java waiting for Input String
```

```
*elapsed-time*
1.0738759

*elapsed-time-count*
1

*elapsed-time*
24.727696700000006

*elapsed-time-count*
30

(/ *elapsed-time* *elapsed-time-count*)
0.8242565566666669
```

**Comment by codeasone** [comment]
+1 this is definitely an area where Intellij is leading the way.

https://plugins.jetbrains.com/plugin/7017-plantuml-integration

Updates happen in real-time as you edit the plantuml mark-up.

**Comment by skuro** [comment]
@codeasone indeed, the fact that Intellij runs a JVM helps when using java tooling

**Comment by terlar** [comment]
Just for reference the plugin for plantuml for visual studio code works quite well in this manner, and that is not JVM based. Might be able to draw some inspiration from that: https://github.com/qjebbs/vscode-plantuml

**Comment by skuro** [comment]
Closing this issue as [we now support server rendering](https://github.com/skuro/plantuml-mode#configure-server-rendering), which is pretty much the same as vsxode
