### ISSUE TITLE
Support for indentation

### ISSUE THREAD

**Issue by terlar** [skuro/plantuml-mode#28]
If you have this code:

``` plantuml_
@startuml

participant API
participant Instance

alt deploy success
    Instance -> API: Deploy successful
else deploy failure
    Instance -> API: Deploy failed
else deploy timeout
    Instance -> API: Deploy failed
end

@enduml
```
1. Move to start of `alt` block.
2. Press `C-SPC`.
3. Move to end of `alt` block.
4. Press `M-C-\` to reformat block.

Expected: The cases should stay indented.
Actual  : The cases lose their indentation and ends up on the same column as
the other parts.

I discovered this since I am using the agressive-indentation mode which
reformats the code all the time.

**Comment by skuro** [comment]
Right, at this moment `plantuml-mode` doesn't support indentation. I have to read up a bit before implementing it, as I have no clue how indentation works for Emacs major modes :-)

**Comment by skuro** [comment]
For future reference: an example from [the Julia mode](https://github.com/JuliaLang/julia/blob/76df7f48b3956de7d2eb07a15c995c9304d5361f/contrib/julia-mode.el#L378)

**Comment by cwdurst** [comment]
Perhaps you can integrate the indentation code from this project:

https://github.com/wildsoul/plantuml-mode

(Disclaimer: I have nothing to do with that project, it's just a feature I'd like to see in this one.)

**Comment by skuro** [comment]
@cwdurst I'll have a look, thanks for pointing it out

**Comment by urugang** [comment]
some workaround is to derive from python-mode.  
I try to use syntax table, but failed. 
It seems that plantuml-mode-syntax-table is not refered by any code.
```
-(define-derived-mode plantuml-mode prog-mode "plantuml"
+(define-derived-mode plantuml-mode python-mode "plantuml"
```

**Comment by skuro** [comment]
Currently implemented via bizantine yet working regex'es. Closing this issue for now, anybody feeling like implementing a proper parser will be welcome but I don't expect it to be an easy task since PlantUML is more of a family of languages rather than a consistent one.
