### ISSUE TITLE
Unable to access to jar file

### ISSUE THREAD

**Issue by windrg** [skuro/plantuml-mode#43]
# Summary

Hi,
Whenever opening a plantuml file, it shows "Error : Unable to access to jar file ..."

I didn't change anything except this

```

(use-package plantuml-mode
     :ensure t
      :init
       (setq plantuml-jar-path "~/.emacs.d/orgtools/plantuml.jar")
      :config
      (add-to-list 'auto-mode-alist '("\\.uml\\'" . plantuml-mode))
      (add-to-list 'auto-mode-alist '("\\.plantuml\\'" . plantuml-mode))
  )
```

However I could launch it without any problem in a terminal.
Could you let me know what could be the problem on opening uml files in Emacs, please??

**Comment by windrg** [comment]
I've added this config but it still complains like the above.

`	(setq plantuml-java-args '("-jar"))`

**Comment by skuro** [comment]
That error message is displayed when `plantuml-mode` cannot find the PlantUML jar file specified at `plantuml-jar-path`. Could you please specify:

- what environment are you running (OS / Emacs version)
- the rest of the error message (i.e. after `Unable to access jar file..`)

Of course, make sure that the file at `~/.emacs.d/orgtools/plantuml.jar` actually exists and is the version of PlantUML that you want to use.

**Comment by windrg** [comment]
Hi,
After updating this package to the recent one, I've tested it again.
And here are my environment and test result
- OS : Ubuntu 16.04 / Emacs 25.1
- Error Messages 
  . message buffer
   `error in process sentinel: PLANTUML Preview failed: exited abnormally with code 1`
  . plantuml message buffer 
   `Command is [-jar|~/.emacs.d/orgtools/plantuml.jar|-charset|UTF-8|-language]`

I've double-checked that it exists in ~/.emacs.d/orgtools/plantuml.jar.

**Comment by windrg** [comment]
I've found somethig new in *Plantuml Preview* which could be a clue for this problem.

`
Error: Unable to access jarfile \~/.emacs.d/orgtools/plantuml.jar`


Could you figure out why it has the prefix / in that path, please?

**Comment by skuro** [comment]
Mhhh that might be because of `shell-quote-argument`. Can you try with the full `/home/<user>/.emacs.d/orgtools/plantuml.jar` path?

**Comment by windrg** [comment]
Yes, it was the culprit. and after doing some tests, I've figured out the below syntax is more appropirate.

`(setq plantuml-jar-path (expand-file-name "~/.emacs.d/orgtools/plantuml.jar"))`

Thanks for helping me.

**Comment by skuro** [comment]
Glad to hear that you found a solution, but I'd like to keep the issue open: it would be best for `plantuml-mode` to actually support `~/path/to/plantuml.jar` styles of configurations.

**Comment by skuro** [comment]
As of ba7420b paths with `~` should be properly expanded, and version `v1.2.1`was just released to include the change.

Thanks for all the testing!
