### ISSUE TITLE
Fail to get picture result unless I run Emacs as root

### ISSUE THREAD

**Issue by zharmand** [skuro/plantuml-mode#54]
If I run Emacs as root, I can get the picture after I press "C-c C-c".
But if I run Emacs as a normal role, I will just get a blank square in plantuml preview mode.
It's strange. Does some command need root privilege when producing the result?

Emacs version : 24.4.1
Java -version :
          Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
          java version "1.8.0_72"
          Java(TM) SE Runtime Environment (build 1.8.0_72-b15)
          Java HotSpot(TM) 64-Bit Server VM (build 25.72-b15, mixed mode)

**Comment by skuro** [comment]
Ideally no command requires root to run. I'm unfamiliar with the agent you're using, what happens if you try the following on the command line (make sure to use the same path to the plantuml JAR file that `plantuml-mode` uses):

    java -jar ${path_to_plantuml.jar} -version

**Comment by zharmand** [comment]
`java -jar plantuml.jar -version`
The result :
```
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
PlantUML version 2017.10 (Fri Apr 07 02:43:00 CST 2017)
(GPL source distribution)
Java Runtime: Java(TM) SE Runtime Environment
JVM: Java HotSpot(TM) 64-Bit Server VM
Java Version: 1.8.0_72-b15
Operating System: Linux
OS Version: 3.19.0-26-generic
Default Encoding: UTF-8
Language: en
Country: US
Machine: ubuntu
PLANTUML_LIMIT_SIZE: 4096
Processors: 4
Max Memory: 1,401,946,112
Total Memory: 94,896,128
Free Memory: 87,975,200
Used Memory: 6,920,928
Thread Active Count: 1

The environment variable GRAPHVIZ_DOT has not been set
Dot executable is /usr/bin/dot
Dot version: dot - graphviz version 2.38.0 (20140413.2041)
Installation seems OK. File generation OK

```

**Comment by skuro** [comment]
There's still the agent output which raises my eyebrow:

    Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 

Can you add the following at the beginning of your init file and try again:

```
(setenv "JAVA_TOOL_OPTIONS" "")
```

**Comment by zharmand** [comment]
It seems no difference. Still a blank square.
