### ISSUE TITLE
Need GPLv3+ compatible license.

### ISSUE THREAD

**Issue by milkypostman** [skuro/plantuml-mode#60]
This package is being removed from MELPA because it doesn't currently have a [license compatible with GPLv3 and later](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses) because Emacs is currently licensed with GPLv3 which is not compatible with older versions unless explicitly stated in the copyright header. Sorry for the inconvenience. More information is below. 

Once properly copyrighted please send a PR to MELPA to have the package reinstated.

Assuming that you want to release under "the GPL v3 or any later version", the best way to do that would be to add this permission statement to the library header:

```
;; This file is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 3, or (at your option)
;; any later version.

;; This file is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.
```

Also consider adding a LICENSE file containing the text of the GPL-3. You could add just that file without also adding the above persmission statement, but if you do that, then the "or (at your option) any later version" bit won't be known. So I recommend that you add both the actual license and the permission statement.

If you find the permission statement to be too noisy, then you could instead add one of these following lines to the header. If you do that, then it becomes more important to also add the LICENSE file - a judge might decide that such a line by itself is not sufficient. Still, adding just such a line is better than not specifing the license at all.

```
;; License: GNU General Public License version 3, or (at your option) any later version
;; License: GNU General Public License version 3, or any later version
;; License: GNU GPL version 3, or (at your option) any later version
;; License: GPL version 3, or (at your option) any later version
;; License: GPL version 3, or any later version
;; License: GPL v3, or (at your option) any later version
;; License: GPL v3, or any later version
;; License: GPL-3+
```

**Comment by skuro** [comment]
Released `v1.2.4` with the same codebase as `v1.2.3`, now licensed as GPLv3+. The PR to MELPA [is already open](https://github.com/melpa/melpa/pull/4946).

Thanks for putting together all the details in the issue description, that helped a lot getting this resolved faster.
