### ISSUE TITLE
plantuml-java-args ignored

### ISSUE THREAD

**Issue by ivan-m** [skuro/plantuml-mode#64]
I need to use a proxy to get access to the internet, so I need to tell java how to do so (as I'm trying to use [AWS-PlantUML](https://github.com/milo-minderbinder/AWS-PlantUML)).

As such, I have this in my configuration:

```elisp
(add-to-list 'plantuml-java-args "-Dhttps.proxyHost=127.0.0.1")
(add-to-list 'plantuml-java-args "-Dhttps.proxyPort=3129")))
```

Doing `C-h v plantuml-java-args` shows that the list is indeed being updated.

Running `plantuml-preview` on a simple PlantUML diagram works.  However, even this one hangs:

```plantuml
@startuml
!includeurl https://raw.githubusercontent.com/milo-minderbinder/AWS-PlantUML/release/17-10-18/dist/common.puml

Alice -> Bob: test
@enduml
```

If I run `list-processes`, I get:

```
PLANTUML        run     *PLANTUML Pr... --           java -Djava.awt.headless=true -jar /Users/ivan/.nix-profile/lib/plantuml.jar -tpng -charset UTF-8 -p
```

That is, the extra arguments I added to `plantuml-java-args` are not appearing in the argument list.

**Comment by skuro** [comment]
fixed by #82
