### ISSUE TITLE
Use already opened preview window/frame instead of openning a new one

### ISSUE THREAD

**Issue by smaant** [skuro/plantuml-mode#65]
# Summary

Now every time I call for preview, new window or frame is created. It would be awesome if already opened preview window/frame exists then just refresh image in that window/frame.

**Comment by transducer** [comment]
You can do that with `C-u C-c C-c`. But the focus does switch to the already opened preview as mentioned in https://github.com/skuro/plantuml-mode/issues/66.

**Comment by wailo** [comment]
I believe this PR #93 addresses this issue. I will appreciate if you can try it and provide feedback

**Comment by skuro** [comment]
Fixed by #93, closign
