### ISSUE TITLE
Stop stealing focus to the preview buffer

### ISSUE THREAD

**Issue by tko** [skuro/plantuml-mode#66]
# Summary

I'm trying to keep an mostly/always visible preview next to the file I'm editing, somewhat along the lines of #65 I imagine -- I can do this with `(plantuml-preview 4)` and it more or less works

...except that that buffer always steals the keyboard focus so that I can't just continue editing but rather always need to manually switch back to the editing. I've tried wrapping my call in `(save-current-buffer)` and others but it seems plantuml is switching to the buffer only after a random delay making it ineffective in practice.

Please allow updating a preview without switching to that buffer.

**Comment by floppydisken** [comment]
I have the same issue, I even tried writing a little elisp function to switch back to the previous window, with no luck. I might've messed up the function, here it is for inspection.
``` elisp
(add-hook 'plantuml-mode-hook
            (lambda ()
              (add-hook 'before-save-hook
                        (lambda ()
                          (plantuml-preview 4)
                          (evil-window-prev))
                        nil 'local)))
```
It hooks onto the save of the plantuml-mode, and tries to switch to the other window after preview has been initiated. It ends up switching to the previous buffer before the new preview window has appeared, rendering the snippet useless.

**Comment by wailo** [comment]
PR https://github.com/skuro/plantuml-mode/pull/93 addresses this issue. I will appreciate if you can try it and provide feedback

**Comment by skuro** [comment]
Yep, I will have a look at #93 shortly, stay tuned for updates

**Comment by skuro** [comment]
Closing as #93 is merged / released
