### ISSUE TITLE
plantuml preview failed exited abnormally with code 1

### ISSUE THREAD

**Issue by dbrw** [skuro/plantuml-mode#70]
# Summary
I see issue #10 and I have same problem so instead waking up old issue, I create this new issue since my configuration different. This is my configuration:
- OS: arch linux
- emacs 25.3.1 with spacemacs 0.200.13
- plantuml version: 1.2018.01
- plantuml path: `/usr/bin/plantuml`
- `plantuml-jar-path` and `org-plantuml-jar-path` variables set to `/usr/bin/plantuml`

The full error when running preview:
```
error in process sentinel: PLANTUML Preview failed: exited abnormally with code 1
```

**Comment by l4ces** [comment]
I understand that you are on linux but this is just food for thought. I encountered this problem on Windows 10 after I edited the path for plantuml.
I then reverted the path to its default and copied the jar file to it. Problem solved.
Again, just one more issue that points to the path.

**Comment by skuro** [comment]
@dbrw It occurs to me that you're trying to execute PlantUML as an program rather than as a Java JAR file. This is not currently supported, see #91

**Comment by rodrigocanellas** [comment]
Hi!

I am using `GNU Emacs 25.3.1 (x86_64-w64-mingw32)`, on `Windows 10`,  `plantuml 1.4.1`, and the following `.emacs`:
```

;; Added by Package.el.  This must come before configurations of
;; installed packages.  Don't delete this line.  If you don't want it,
;; just comment it out by adding a semicolon to the start of the line.
;; You may delete these explanatory comments.
(package-initialize)

(require 'package)
(add-to-list 'package-archives
             '("MELPA Stable" . "http://stable.melpa.org/packages/") t)






(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages (quote (plantuml-mode ## flycheck company)))
 '(plantuml-default-exec-mode (quote jar))
 '(plantuml-jar-path "C:\\Users\\tc000210\\AppData\\Roaming\\plantuml.jar"))

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )


;;(setq plantuml-jar-path "C:\\Users\\tc000210\\AppData\\Roaming\\plantuml.jar")
;;(setq plantuml-default-exec-mode 'jar)

;;(with-eval-after-load 'flycheck
;;  (require 'flycheck-plantuml)
;;  (flycheck-plantuml-setup))

(add-to-list 'auto-mode-alist '("\\.plantuml\\'" . plantuml-mode))
```

When I try to execute `plantuml-preview` on this PlantUML code:
```
@startuml

A *-- B

@enduml
```

I get the message `error in process sentinel: PLANTUML preview failed: exited abnormally with code 1`

Does anyone know how to fix this?

Thanks!

**Comment by zhenwenc** [comment]
I got the same error message as well, but the issue was caused by an invalid Java argument `--illegal-access=deny` (see default value of `plantuml-java-args` variable).

This argument was introduced at Java 9, but I am currently using Java 8.

As a side note, when the command is failed, you can manually jump to the `*PLANTUML Preview*` buffer to see the actual error message.

**Comment by lucasalencar** [comment]
To avoid this error I reset the `plantuml-java-args` to remove the argument that was causing the error.

```elisp
(setq plantuml-java-args (list "-Djava.awt.headless=true" "-jar"))
```

**Comment by frgomes** [comment]
Just one more contribution here.
I'm using PlantUML on a Debian Buster with openjdk-11-jre
My configuration works pretty well now after trying different approaches.

```lisp
(use-package plantuml-mode
  :init
    (setq plantuml-default-exec-mode 'jar)
    (setq plantuml-jar-path "/usr/share/plantuml/plantuml.jar")
    (setq org-plantuml-jar-path (expand-file-name "/usr/share/plantuml/plantuml.jar"))
    (setq org-startup-with-inline-images t)
    (add-to-list 'org-src-lang-modes '("plantuml" . plantuml))
    (org-babel-do-load-languages 'org-babel-load-languages '((plantuml . t))))
```
