### ISSUE TITLE
auto-indentation jumps to the previous line

### ISSUE THREAD

**Issue by rymndhng** [skuro/plantuml-mode#77]
# Summary

> When using auto-indentation, the cursor appears to jump to the previous line

![funkiness](https://user-images.githubusercontent.com/1694040/44223270-06438c80-a13c-11e8-8059-162cb8172727.gif)

# Checklist for pull requests

- [ ] I'm fine with my code being released under the GPLv2 license
- [ ] the pull request is filed against the `develop` branch instead of `master`

**Comment by skuro** [comment]
Should be fixed in the latest `plantuml-mode` release (v.1.2.8)
