### ISSUE TITLE
How to disable indent mode of plantuml ? 

### ISSUE THREAD

**Issue by dinuscxj** [skuro/plantuml-mode#80]
# Summary

> Because the indent mode of plantuml not work well,  so I want to disable the indent mode of plantuml

**Comment by accakiba** [comment]
Applying this patch will work, but large files may be slow.

--- plantuml-mode.el.orig       2018-11-20 14:26:39.769035112 +0900
+++ plantuml-mode.el    2018-11-20 14:23:57.315849112 +0900
@@ -409,8 +409,7 @@
           (bob-visited? nil))
       (beginning-of-line)
       (forward-line -1)
-      (while (and (>= relative-depth 0)
-                  (not bob-visited?))
+      (while (not bob-visited?)
         (if (bobp)
             (setq bob-visited? t))
         (if (looking-at plantuml-indent-regexp-end)

**Comment by skuro** [comment]
Disabling indentation is currently not supported, sorry
