### ISSUE TITLE
Unable to modify variable plantuml-java-args

### ISSUE THREAD

**Issue by niklascarlsson** [skuro/plantuml-mode#81]
# Summary

Hi! 

Thank you skuro for a great package, I am using your plantuml-mode in my daily work :). Recently there has been some changes to a couple of plantuml files so in order to build them one must provide the path to the project root.

I wanted to make so I could continue working with those files using Emacs and not have to rely upon the terminal to build those files.  So I found the variable `plantuml-java-args`.

I decided first to add the following to my emacs.d confifguration: 
```(require plantuml-mode)
(add-to-list 'plantuml-java-args "Dplantuml.include.path=path_to_project_root")
```
But it didn't seem to have any effect.

Then I started looking into the `plantuml.el` file and found this part
```
(eval-and-compile
  (defcustom plantuml-java-args (list " "-Djava.awt.headless=true" "-jar")
    "The parameters passed to `plantuml-java-command' when executing PlantUML."
    :type '(repeat string)
    :group 'plantuml))
```
Now my elisp knowledge is not that great so I am not entirely sure I understand the need for the `eval-and-compile` here, but it seems like it makes it not possible for me to change this variable after it has been compiled. 

I have gotten around the issue in two ways either by modifying the source code and add my path to the defcustom part above and compile the code. Or to change the source code to remove `the eval-and-compile` and then ad the `add-to-list` in my configuration.

Could you provide input on how I could solve this in any other way then having to hack into the source code? Ideally it would be great if I could modify the java-args by using the `add-to-list` so that I could utilize that in a dir-locals.el since this argument is project specific :)

**Comment by niklascarlsson** [comment]
I opened a pull request which addresses this issue, it can be found here: https://github.com/skuro/plantuml-mode/pull/82

**Comment by skuro** [comment]
I'm gonna close this issue as #81 was just merged. Thanks for your help!
