### ISSUE TITLE
Cannot set plantuml-set-exec-mode to jar

### ISSUE THREAD

**Issue by lockywolf** [skuro/plantuml-mode#97]
# Summary

I am running `M-x plantuml-set-exec-mode RET jar RET`
I am getting the following error:
 `command-execute: Wrong type argument: listp, "jar"`

`M-x plantuml-set-exec-mode RET server RET`
also fails with a different error:
`command-execute: Wrong type argument: sequencep, server`

What am I doing wrong?

plantuml-mode  plantuml-mode      20190531.853 from MELPA

**Comment by joe-mcnuggets** [comment]
Possible workaround is adding `'(plantuml-default-exec-mode "jar")` to your emacs config. Worked for me

**Comment by dcreemer** [comment]
I added this `(plantuml-set-exec-mode "jar")` to my emacs init.el

**Comment by ahmed-shariff** [comment]
I am also getting the same error.
Even when i set `plantuml-default-exec-mode` or call `plantuml-set-exec-mode` it still tries to connect to `www.plantuml.com:443`

**Comment by hubisan** [comment]
If using a elisp expressions as arg-descriptor for interactive it has to return a list: https://www.gnu.org/software/emacs/manual/html_node/elisp/Using-Interactive.html#Using-Interactive.

So to fix this error the completing-read part should return a list as follows:

```emacs-lisp
(defun plantuml-set-exec-mode (mode)
  "Set the execution mode MODE for PlantUML."
  (interactive (let* ((completion-ignore-case t)
                      (supported-modes        '("jar" "server")))
                 (list (completing-read (format "Exec mode [%s]: " plantuml-exec-mode)
                                        supported-modes
                                        nil
                                        t
                                        nil
                                        nil
                                        plantuml-exec-mode))))
  (if (member mode '("jar" "server"))
      (setq plantuml-exec-mode (intern mode))
    (error (concat "Unsupported mode:" mode))))
```

**Comment by OiTAvO** [comment]
> If using a elisp expressions as arg-descriptor for interactive it has to return a list: https://www.gnu.org/software/emacs/manual/html_node/elisp/Using-Interactive.html#Using-Interactive.
> 
> So to fix this error the completing-read part should return a list as follows:
> 
> ```emacs-lisp
> (defun plantuml-set-exec-mode (mode)
>   "Set the execution mode MODE for PlantUML."
>   (interactive (let* ((completion-ignore-case t)
>                       (supported-modes        '("jar" "server")))
>                  (list (completing-read (format "Exec mode [%s]: " plantuml-exec-mode)
>                                         supported-modes
>                                         nil
>                                         t
>                                         nil
>                                         nil
>                                         plantuml-exec-mode))))
>   (if (member mode '("jar" "server"))
>       (setq plantuml-exec-mode (intern mode))
>     (error (concat "Unsupported mode:" mode))))
> ```

Thank you! This solves the problem.

**Comment by skuro** [comment]
Thank you @hubisan for spotting the issue! I integrated your solution in the code and cut a release of `plantuml-mode` which should appear soonish on MELPA
